In [2]:
(u,Σ,V) = svd(M)

(
8x8 Array{Float64,2}:
 -0.313773   0.63047     0.509089   …  -0.124343    0.0858669   0.428752 
 -0.239098  -0.421986    0.237885       0.546886    0.377526    0.0808479
 -0.233683   0.130696   -0.423489      -0.424318    0.657189   -0.242519 
 -0.412169   0.0493972  -0.444988       0.236437    0.127271    0.462627 
 -0.410774  -0.398549   -0.0854409     -0.507075   -0.465753    0.22819  
 -0.444841   0.320308   -0.287358   …   0.414901   -0.414599   -0.393212 
 -0.447415  -0.0940023   0.450951      -0.141698    0.0708032  -0.54908  
 -0.230409  -0.366933    0.116835      -0.0126462   0.0904118   0.169177 ,

[4.19452,1.25402,1.07033,0.703226,0.405024,0.389118,0.209766,0.00301578],
8x8 Array{Float64,2}:
 -0.227403   0.616998     0.356737   …   0.257333   -0.582176   -0.0474541
 -0.360254  -0.3932      -0.222614       0.707382   -0.0134694   0.180096 
 -0.352619   0.356669    -0.405272      -0.442152    0.192603    0.222521 
 -0.322331  -0.231076     0.69905       -0.152859    0.306367

In [4]:
M2 = u*diagm(Σ)*V'

8x8 Array{Float64,2}:
 0.979053   0.0574943  0.625941  0.680437   …  0.63893    0.265102  0.22123 
 0.0242542  0.747997   0.125055  0.734075      0.141846   0.439489  0.309876
 0.0687576  0.34185    0.795251  0.0944498     0.438603   0.315003  0.439613
 0.205472   0.62006    0.564967  0.0750416     0.972013   0.842372  0.799202
 0.0689152  0.75276    0.625578  0.6888        0.307107   0.952499  0.830377
 0.69344    0.779413   0.956258  0.300111   …  0.803604   0.589428  0.716873
 0.447356   0.445383   0.255756  0.872008      0.706729   0.899158  0.733092
 0.0137118  0.536246   0.161803  0.448824      0.0254878  0.274136  0.651029

In [6]:
delta = M2-M

8x8 Array{Float64,2}:
 -1.11022e-15   1.11716e-15  -1.11022e-16  …   5.55112e-16   4.44089e-16
  2.28983e-16   3.33067e-16  -5.55112e-17      5.55112e-17   2.77556e-16
  2.22045e-16   0.0          -2.22045e-16     -5.55112e-17  -1.66533e-16
  3.60822e-16   5.55112e-16  -1.11022e-16     -2.22045e-16  -1.11022e-16
  3.60822e-16  -5.55112e-16   2.22045e-16     -2.22045e-16  -1.11022e-16
  0.0           5.55112e-16  -3.33067e-16  …  -1.11022e-16  -2.22045e-16
 -1.11022e-16   4.996e-16     3.88578e-16      1.11022e-16   2.22045e-16
  2.42861e-16   0.0           1.38778e-16     -5.55112e-17  -1.11022e-16

In [1]:
M = rand(8,8)

8x8 Array{Float64,2}:
 0.979053   0.0574943  0.625941  0.680437   …  0.63893    0.265102  0.22123 
 0.0242542  0.747997   0.125055  0.734075      0.141846   0.439489  0.309876
 0.0687576  0.34185    0.795251  0.0944498     0.438603   0.315003  0.439613
 0.205472   0.62006    0.564967  0.0750416     0.972013   0.842372  0.799202
 0.0689152  0.75276    0.625578  0.6888        0.307107   0.952499  0.830377
 0.69344    0.779413   0.956258  0.300111   …  0.803604   0.589428  0.716873
 0.447356   0.445383   0.255756  0.872008      0.706729   0.899158  0.733092
 0.0137118  0.536246   0.161803  0.448824      0.0254878  0.274136  0.651029

In [12]:
w = [1.,1.]
M = reshape([2.,1.,1.,1.],(2,2))


2x2 Array{Float64,2}:
 2.0  1.0
 1.0  1.0

In [14]:
w = [1.,1.]
for i in 1:10
    w_new = M*w
    w_new = w_new/norm(w_new)
    println(w_new)
    w = w_new
end

[0.8320502943378436,0.554700196225229]
[0.847998304005088,0.52999894000318]
[0.8502651466878618,0.5263546146162954]
[0.8505945695460382,0.5258220975375509]
[0.8506426038271653,0.525744387087623]
[0.8506496113409004,0.5257330489189119]
[0.850650633710743,0.5257313946945829]
[0.850650782872224,0.5257311533463396]
[0.8506508046345851,0.525731118134102]
[0.8506508078096706,0.5257311129967057]


In [22]:
w = [1.,1.]
maxerr = 1.0e-12
err = 1.0
while (err > maxerr)
    w_new = M*w
    w_new = w_new/norm(w_new)
    println(w_new)
    err = norm(w_new-w)
    w = w_new
end

[0.8320502943378436,0.554700196225229]
[0.847998304005088,0.52999894000318]
[0.8502651466878618,0.5263546146162954]
[0.8505945695460382,0.5258220975375509]
[0.8506426038271653,0.525744387087623]
[0.8506496113409004,0.5257330489189119]
[0.850650633710743,0.5257313946945829]
[0.850650782872224,0.5257311533463396]
[0.8506508046345851,0.525731118134102]
[0.8506508078096706,0.5257311129967057]
[0.8506508082729094,0.5257311122471696]
[0.8506508083404949,0.5257311121378138]
[0.8506508083503556,0.525731112121859]
[0.8506508083517942,0.5257311121195312]
[0.850650808352004,0.5257311121191915]


In [23]:
M = rand(100,100)
M2 = map(big, M)
lu(M2)

(
100x100 Array{BigFloat,2}:
 1e+00                                                                                 …  0e+00
 6.482186325598420372813177870158790435734810000793847332541311929502772453692702e-03     0e+00
 6.497881519197981608398499655690207239441785495763055245000016984954155223466667e-01     0e+00
 9.414917063273450843044092431133848125324278795739051430162286038341805052056216e-01     0e+00
 9.869027116859920817781623602998885459741672250023167394330155237529124769418096e-01     0e+00
 3.606823052470973925981035821034936057896910641086228077420658683511966007680514e-03  …  0e+00
 1.787048066051802174032798918505541898321634203365459108794475171862906595866659e-01     0e+00
 7.446394398489431831368387733697494963469650878433095128650650085418707984434589e-02     0e+00
 3.269692147984345600480662116458466279641153267638912865995958681636108790815817e-01     0e+00
 8.531694771741609286721925367993022705707049535353510221922795329087742246681918e-01     0e+00
 6.08691479

In [24]:
methods(lu)


# 2 methods for generic function "lu":
lu(x::Number) at linalg/lu.jl:69
lu(A::AbstractArray{T,2}) at linalg/lu.jl:71

In [25]:
@edit lu(M2)


Unknown editor: no line number information passed.
The method is defined at line 71.


In [30]:
dup(x) = x^2



dup (generic function with 1 method)

In [31]:
dup(3)


9

In [32]:
dup("hello")

"hellohello"

In [33]:
"gugus" + "Sam"

LoadError: `+` has no method matching +(::ASCIIString, ::ASCIIString)
while loading In[33], in expression starting on line 1

In [35]:
+(s1::String, s2::String) = string(s1, ":",s2)

+ (generic function with 118 methods)

In [36]:
"gugus" + "Sam"

"gugus:Sam"

In [38]:
@which 3//4



//(n::Integer,d::Integer) at rational.jl:15

**Excercise**: Define a prticle with postion and velocity
 and define Math operation. Define fuction `move` that acts on a particle to move it over a time \delta t

In [56]:
immutable Vector2D
    x::Float64
    y::Float64
end

In [57]:
+(v::Vector2D, w::Vector2D) = Vector2D(v.x+w.x, v.y+w.y)

+ (generic function with 119 methods)

In [58]:
k = Vector2D(2,3)
g = Vector2D(4,5)
g+k

[6.0,8.0]

In [59]:
*(v::Vector2D, α::Number) = Vector2D(v.x*α,v.y*α)

* (generic function with 117 methods)

In [60]:
*( α::Number, v::Vector2D) = Vector2D(v.x*α,v.y*α)

* (generic function with 117 methods)

In [61]:
4*g


[16.0,20.0]

In [62]:
import Base.show

show(io::IO, v::Vector2D) = print(io, "[$(v.x),$(v.y)]")

show (generic function with 86 methods)

In [63]:
g

[4.0,5.0]

In [74]:
type Particle
    position::Vector2D
    velocity::Vector2D
end

move(p::Particle, dt::Real) = p.position += p.velocity*dt


move (generic function with 1 method)

In [75]:
show(io::IO, p::Particle) = print(io, "pos: $(p.position); vel: $(p.velocity)")

show (generic function with 87 methods)

In [76]:
P = Particle(Vector2D(0.,0.),Vector2D(1.,1.))

pos: [0.0,0.0]; vel: [1.0,1.0]

In [77]:
move(P,0.1)


[0.1,0.1]

In [78]:
P

pos: [0.1,0.1]; vel: [1.0,1.0]