In [1]:
# Imports and setting up
import numpy as np

num_cities = 4
length_of_tour = num_cities

cities_with_distances = {
    1: {2: .1, 3: .1, 4: .1},
    2: {1: .1, 3: .1, 4: .1},
    3: {1: .1, 2: .1, 4: .1},
    4: {1: .1, 2: .1, 3: .1},
}

num_vars = length_of_tour * num_cities

# Define distances-- hardcoded for this example
distances = [[ 0., 0.1, 0.1, 0.1],
             [0.1, 0. , 0.1, 0.1],
             [0.1, 0. , 0.1, 0.1],
             [0.1, 0. , 0.1, 0.1]]

In [3]:
# Define the initial QUBO
Q = [[0 for _ in range(num_vars)] for _ in range(num_vars)]
print (np.vstack(Q))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [5]:
from itertools import combinations

#Assert that every city is only visited once
for step_i in range(length_of_tour):
    # Add linear terms
    for city_i in range(num_cities):
        i = city_i * num_cities
        Q[i + step_i][i + step_i] += -1
        
    # Add cross-terms
    for city_i, city_j in sorted(combinations(range(num_cities), 2)):
        i = city_i * num_cities
        j = city_j * num_cities
        if i < j:
            Q[i+step_i][j+step_i] += 2
            
print (np.vstack(Q))

[[-1  0  0  0  2  0  0  0  2  0  0  0  2  0  0  0]
 [ 0 -1  0  0  0  2  0  0  0  2  0  0  0  2  0  0]
 [ 0  0 -1  0  0  0  2  0  0  0  2  0  0  0  2  0]
 [ 0  0  0 -1  0  0  0  2  0  0  0  2  0  0  0  2]
 [ 0  0  0  0 -1  0  0  0  2  0  0  0  2  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0  2  0  0  0  2  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0  2  0  0  0  2  0]
 [ 0  0  0  0  0  0  0 -1  0  0  0  2  0  0  0  2]
 [ 0  0  0  0  0  0  0  0 -1  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 -1  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 -1  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]]


In [6]:
# Assert every step in the path is visited once for each city
for city_i in range(num_cities):
    i = city_i * num_cities
    # Linear terms
    for step_i in range(length_of_tour):
        Q[i+step_i][i+step_i] += -1
        
    # Add cross-terms
    for step_i, step_j in sorted(combinations(range(length_of_tour), 2)):
        if step_i < step_j:
            Q[i+step_i][i+step_j] += 2

print (np.vstack(Q))

[[-2  2  2  2  2  0  0  0  2  0  0  0  2  0  0  0]
 [ 0 -2  2  2  0  2  0  0  0  2  0  0  0  2  0  0]
 [ 0  0 -2  2  0  0  2  0  0  0  2  0  0  0  2  0]
 [ 0  0  0 -2  0  0  0  2  0  0  0  2  0  0  0  2]
 [ 0  0  0  0 -2  2  2  2  2  0  0  0  2  0  0  0]
 [ 0  0  0  0  0 -2  2  2  0  2  0  0  0  2  0  0]
 [ 0  0  0  0  0  0 -2  2  0  0  2  0  0  0  2  0]
 [ 0  0  0  0  0  0  0 -2  0  0  0  2  0  0  0  2]
 [ 0  0  0  0  0  0  0  0 -2  2  2  2  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 -2  2  2  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 -2  2  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 -2  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 -2  2  2  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 -2  2  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 -2  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -2]]


In [8]:
# Add the distances into the QUBO

for city_i, city_j in sorted(combinations(range(num_cities), 2)):
    if city_i != city_j:
        i = city_i * num_cities
        j = city_j * num_cities
        distance = distances[city_i][city_j]
        
        # Add distances on the cross-terms
        for step_i in range(length_of_tour-1):
            Q[i+step_i][j+step_i+1] += distance
        # don't forget the last step!
        Q[i + num_cities - 1][j] += distance
            
print (np.vstack(Q))

[[-2.   2.   2.   2.   2.   0.2  0.   0.   2.   0.2  0.   0.   2.   0.2  0.
   0. ]
 [ 0.  -2.   2.   2.   0.   2.   0.2  0.   0.   2.   0.2  0.   0.   2.   0.2
   0. ]
 [ 0.   0.  -2.   2.   0.   0.   2.   0.2  0.   0.   2.   0.2  0.   0.   2.
   0.2]
 [ 0.   0.   0.  -2.   0.2  0.   0.   2.   0.2  0.   0.   2.   0.2  0.   0.
   2. ]
 [ 0.   0.   0.   0.  -2.   2.   2.   2.   2.   0.2  0.   0.   2.   0.2  0.
   0. ]
 [ 0.   0.   0.   0.   0.  -2.   2.   2.   0.   2.   0.2  0.   0.   2.   0.2
   0. ]
 [ 0.   0.   0.   0.   0.   0.  -2.   2.   0.   0.   2.   0.2  0.   0.   2.
   0.2]
 [ 0.   0.   0.   0.   0.   0.   0.  -2.   0.2  0.   0.   2.   0.2  0.   0.
   2. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -2.   2.   2.   2.   2.   0.2  0.
   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  -2.   2.   2.   0.   2.   0.2
   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -2.   2.   0.   0.   2.
   0.2]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -2.   0.2  0.   

In [10]:
# Check that everything works with one good tour and one bad tour:
good_tour = [1, 0, 0, 0,
             0, 1, 0, 0, 
             0, 0, 1, 0, 
             0, 0, 0, 1]

bad_tour = [1, 0, 0, 0,
            0, 1, 0, 0, 
            0, 0, 1, 0, 
            1, 0, 0, 0]

good_tour = np.array(good_tour)
bad_tour = np.array(bad_tour)

print ('Good tour objective:')
print (np.dot(good_tour, Q).dot(good_tour.T))

print ('Bad tour objective:')
print (np.dot(bad_tour, Q).dot(bad_tour.T))

Good tour objective:
-7.4
Bad tour objective:
-5.6
